README.md, pages/home.py, setup.cfg, tests/conftest.py, tests/test_cnx_home.py
* Added flake8 rule to extend line length to 100 characters¬
* Added Book Region to Home page¬
* Added Featured Books locator for openstax books and cnx books¬
* Fixed Home page wait_for_page_load to openstax books in featured¬
books.¬
=> Added test to check for loading of featured books¬

pages/content.py, pages/home.py, tests/test_cnx_home.py
* Added test to click book cover link and check book content loads
* Added test to click title link and check book content loads
* Added test to click read more and check book content loads
=> Added tests to home page for clicking various book links

pages/home.py, tests/test_cnx_home.py
* Changed book.name to book.title
=> added given when then statements to all tests

tests/conftest.py, tests/utils.py
Refactor gen_list_from_file() to generator_from_file()
=> Fixed gen_list_from_file function #9

README.md
* added the travis badge so that we know master was built successfully.
=> added travis badge to readme

pages/webview/base.py, pages/webview/content.py, pages/webview/home.py
Reverts openstax/cnx-automation#26
=> Revert "Fix webview stale element errors"

fixtures/base.py, fixtures/legacy.py, fixtures/webview.py, pages/webview/base.py, pages/webview/content.py, pages/webview/home.py
Tried a ton of stuff to get rid of the stale element errors.
=> Fix webview stale errors

.travis.yml, docker-compose.yml
* Pull docker image from the openstax docker hub repository in order to speed up travis build time
* Update the docker-compose file to reflect this change
* Update .travis.yml to reflect this change
=> Pull docker image from the openstax docker hub repository

.gitignore, Dockerfile, Makefile, README.md, tox.ini
* Updated README to include docker instructions
* Added Makefile with commands that allow cleaning of pyc files and
other build files.
* Updated Dockerfile to install python3.6
* Added .DS_Store to .gitignore
* Added python3.6 to testenv in tox.ini
=> Updated Dockerfile to install python3.6 and updated README

pages/webview/base.py, pages/webview/home.py, tests/webview/ui/test_browse.py, tests/webview/ui/test_home.py
https://github.com/openstax/cnx-automation/issues/34
=> Added tests for clicking the CNX logo

fixtures/base.py, pages/webview/browse.py, pages/webview/search_results.py, tests/webview/ui/test_browse.py
https://github.com/openstax/cnx-automation/issues/41
Let me know if I should test for the Polish message too.
=> Added webview test for searching and finding no results

pages/webview/browse.py, tests/webview/ui/test_browse.py
https://github.com/openstax/cnx-automation/issues/40
=> Test that the browse subjects have greater-than-zero page and book counts

pages/webview/base.py, pages/webview/donate.py, pages/webview/donate_form.py, tests/webview/ui/test_donate.py
https://github.com/openstax/cnx-automation/issues/49
https://github.com/openstax/cnx-automation/issues/50
https://github.com/openstax/cnx-automation/issues/51
https://github.com/openstax/cnx-automation/issues/52
For #50, we are testing only that the form action url is correct, since the ebank page does not display any info other than the value.
For #52, we are testing only that the inputs have the HTML5 required attribute. The message is handled by the browser and seems to not be accessible through the DOM.
=> Donation tests

pages/archive/content.py, pages/archive/legacy_content.py, pages/legacy/base.py, pages/legacy/cc_license.py, pages/legacy/login_form.py, pages/legacy/module_confirm_publish.py, pages/legacy/module_edit.py, pages/legacy/module_import.py, pages/legacy/module_metadata.py, pages/legacy/module_publish.py, pages/legacy/my_dashboard.py, pages/legacy/published_module.py, pages/webview/about_page.py, pages/webview/about_us.py, pages/webview/base.py, pages/webview/browse.py, pages/webview/contact.py, pages/webview/content.py, pages/webview/donate.py, pages/webview/donate_form.py, pages/webview/home.py, pages/webview/search_results.py, regions/legacy/my_account.py, regions/webview/__init__.py, regions/webview/base.py, tests/webview/ui/test_about.py, tests/webview/ui/test_contact.py
https://github.com/openstax/cnx-automation/issues/42
https://github.com/openstax/cnx-automation/issues/43
https://github.com/openstax/cnx-automation/issues/44
https://github.com/openstax/cnx-automation/issues/45
https://github.com/openstax/cnx-automation/issues/46
https://github.com/openstax/cnx-automation/issues/47
https://github.com/openstax/cnx-automation/issues/48
=> Test About Us and Contact pages

.travis.yml, docker-compose.yml, fixtures/base.py, tests/conftest.py, tox.ini
To help debug sporadic failures
=> Added command line option to print page source on failure and enabled it for Travis

patches/connection_reset_by_peer.py, patches/remote_connection.py, tests/conftest.py, tests/utils.py
Need to run this a bunch and make sure the issue is fixed.
=> Connection reset by peer monkeypatch

pages/webview/contact.py
Before the page is considered loaded
=> Wait for the map in the Contact Us page to at least start loading

tests/webview/ui/test_browse.py
https://github.com/openstax/cnx-automation/issues/84
=> Added missing markers for logo test

pages/webview/donate.py, tests/webview/ui/test_donate.py
https://github.com/openstax/cnx-automation/issues/93
The issue says to drag the slider, but using the action chains to drag seemed very flaky (the size of the bar depends on the screen resolution so calculating offsets would be weird). So I used the keyboard arrow keys instead.
=> Added a test for the donation slider

pages/legacy/confirm_publish.py, pages/legacy/metadata_edit.py, pages/legacy/workspace.py
This PR was going to have some delete test fixes but now that that test has been removed it just has a bit of code cleanup.
=> Small misc cleanup

regions/legacy/add_modules.py, regions/legacy/add_modules_with_search_results.py, regions/legacy/base.py
Should fix stale element error on add_modules search.
=> Split add_modules into 2 regions (pre and post-search) with different loaded methods

pages/legacy/confirm_publish.py, pages/webview/content.py, regions/webview/base.py, regions/webview/content_item.py, tests/utils.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/95
https://github.com/openstax/cnx-automation/issues/96
https://github.com/openstax/cnx-automation/issues/97
https://github.com/openstax/cnx-automation/issues/99
https://github.com/openstax/cnx-automation/issues/100
https://github.com/openstax/cnx-automation/issues/101
https://github.com/openstax/cnx-automation/issues/102
https://github.com/openstax/cnx-automation/issues/103
https://github.com/openstax/cnx-automation/issues/104
https://github.com/openstax/cnx-automation/issues/105
https://github.com/openstax/cnx-automation/issues/106
https://github.com/openstax/cnx-automation/issues/107
https://github.com/openstax/cnx-automation/issues/108
https://github.com/openstax/cnx-automation/issues/109
=> Content page tests

pages/webview/advanced_search.py, pages/webview/base.py, pages/webview/browse.py, pages/webview/content.py, pages/webview/search_results.py, tests/markers.py, tests/webview/ui/test_browse.py
https://github.com/openstax/cnx-automation/issues/85
https://github.com/openstax/cnx-automation/issues/86
https://github.com/openstax/cnx-automation/issues/87
https://github.com/openstax/cnx-automation/issues/88
https://github.com/openstax/cnx-automation/issues/89
https://github.com/openstax/cnx-automation/issues/90
https://github.com/openstax/cnx-automation/issues/91
https://github.com/openstax/cnx-automation/issues/92
=> Search (browse) tests

setup.cfg, tests/markers.py, tests/webview/ui/test_home.py
This will probably fail a lot, because a bunch of books have titles that don't match the home page on both QA and staging.
=> Change default webview url to staging and test 2 random books in each home page test (xfailing tests) 

Makefile, README.md
python-dotenv expects .env to be a file
=> Renamed the make venv dir to .venv so it doesn't collide with .env

pages/webview/search_results.py, tests/webview/ui/test_browse.py
Seems like we want fewer, rarer words.
=> Change our search query for faster searches and hopefully less timeouts

.travis.yml, README.md, docker-compose.yml, fixtures/archive.py, fixtures/base.py, fixtures/legacy.py, fixtures/webview.py, requirements.txt, setup.cfg, tests/conftest.py, tests/utils.py, tests/webview/ui/test_about.py, tests/webview/ui/test_browse.py, tests/webview/ui/test_contact.py, tests/webview/ui/test_content.py, tests/webview/ui/test_donate.py, tests/webview/ui/test_home.py, tox.ini
- Renamed base_url to webview_base_url
- Restored functionality that skips destructive tests on sensitive urls
=> Add WEBVIEW_BASE_URL env var and move Travis back to QA

pages/webview/content.py
The button might not be present until the download tab finishes loading.
=> Wait for the downloads tab to load before starting Get This Book! button tests

pages/webview/home.py, tests/webview/ui/test_home.py
https://github.com/openstax/cnx-automation/issues/38
=> (xfailing test) Verify that all featured books have titles and intros

tests/webview/ui/test_browse.py, tests/webview/ui/test_home.py
=> base_url to webview_base_url variable name change and improved some comments

pages/webview/content.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/145
=> Test that the book author is OpenStax

.gitignore, README.md, requirements.txt, setup.cfg, testrail.example.cfg, tests/markers.py, tests/webview/ui/test_browse.py, tests/webview/ui/test_home.py
* added testrail.example.cfg
* added test case id to featured books test
* added testrail marker to markers.py
* added testrail.cfg to .gitignore
=> Added test rail integration

pages/legacy/collection_edit.py, pages/legacy/metadata_edit.py, pages/legacy/module_edit.py
Combines code to handle both the alert and the SiteError that can happen when submitting the metadata form.
=> Handle unexpected alert on collection creation

pages/webview/base.py, tests/webview/ui/test_browse.py, tests/webview/ui/test_home.py
https://github.com/openstax/cnx-automation/issues/144
=> Added more webview nav tests

pages/webview/content.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/146
=> Test that the section title does not contain HTML markup

pages/webview/base.py, pages/webview/browse.py, pages/webview/content.py, pages/webview/home.py, regions/webview/base.py, tests/webview/ui/test_content.py, tests/webview/ui/test_home.py
https://github.com/openstax/cnx-automation/issues/148
https://github.com/openstax/cnx-automation/issues/149
=> Added tests for id links and the browser's back button

tests/webview/ui/test_content.py
* Added test case id to test_ncy_is_not_displayed in test_content.py for american government
=> Added case id to test_ncy_is_not_displayed

tests/webview/ui/test_browse.py
https://github.com/openstax/cnx-automation/issues/154
=> Added another search test and test case

pages/webview/content.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/152
=> Test that the support email displays properly in the attribution tab

pages/webview/base.py, pages/webview/content.py, tests/webview/ui/test_content.py, tests/webview/ui/test_home.py
https://github.com/openstax/cnx-automation/issues/155
=> Added test for footer elements

pages/webview/content.py
Using the offscreen_click() method
=> Attempt to fix flaky clicks on downloads and attribution tabs

pages/webview/content_status.py, tests/webview/ui/test_content_status.py
https://github.com/openstax/cnx-automation/issues/157
=> Added test for the styles in the Content Status page

fixtures/base.py, pages/webview/content.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/159
=> Added test for the "derived from" text

pages/robots.py, tests/webview/ui/test_robots.py
https://github.com/openstax/cnx-automation/issues/160
https://github.com/openstax/cnx-automation/issues/161
=> Added tests for robots.txt

tests/webview/ui/test_home.py
So we don't reload the home page on the last iteration
=> Small optimization for the 3 home page book tests

tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/162
=> Added test for status code for webview and archive content URLs

pages/webview/content.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/163
=> Test the newer version link

pages/webview/base.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/164
=> Test that the canonical links (kind of) take you to the same page

tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/165
Based on https://github.com/openstax/cnx-automation/pull/210 because I needed the methods I added there to extract versions from the URL
=> Test that the chapter review version matches the book version

pages/webview/content.py, pages/webview/search_results.py, tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/151
https://github.com/openstax/cnx-automation/issues/156
=> Added test for in-book search

pages/webview/content.py, pages/webview/sitemap.py, pages/webview/sitemap_index.py, tests/webview/ui/test_content.py, tests/webview/ui/test_sitemap.py
https://github.com/openstax/cnx-automation/issues/170
=> Added test for sitemap segmented by author

pages/webview/base.py, pages/webview/content.py, regions/webview/base.py, tests/webview/ui/test_content.py, tests/webview/ui/test_home.py
https://github.com/openstax/cnx-automation/issues/168
=> Added test for the content header menu hiding when scrolling on mobile

.travis.yml, tox.ini
=> Python 3.7 and updated Travis to Xenial

tests/webview/ui/test_content.py
@m1yag1 this is a weird test, so take a look and see if you agree with it.
https://github.com/openstax/cnx-automation/issues/167
=> Test that pages with unicode chars in the title load

pages/webview/content.py, pages/webview/content_page.py, tests/webview/ui/test_content.py
=> Book title length limitation

tests/webview/ui/test_content.py
=> add test case for the button text

pages/webview/content.py
=> Hopefully fix stale ToC issues

.travis.yml, pages/webview/base.py, pages/webview/content.py, pages/webview/home.py, tests/utils.py, tests/webview/ui/test_content.py, tests/webview/ui/test_home.py
=> Refactor book and title tests

pages/webview/content.py
try conditional that looks for open class on the toc/book button and does a blind click. blind click meaning that it clicks without worrying about state b/c at this point it knows it is open and simply needs to close it.
=> try conditional for flaky click_contents_button

pages/webview/content.py, tests/webview/ui/test_content.py
Another attempt to fix flakey book button test.
=> added better  locator for toc and used  click_contents_button method to wait for toc to display

tests/webview/ui/test_search.py
tweaked advanced search test so it returned results
=> tweaked advanced search test so it returned results

fixtures/data/legacy/sample_mathml3.cnxml, fixtures/legacy.py, pages/legacy/module_edit.py, tests/legacy/ui/test_create_import_publish_module_and_collection.py
=> Added test for mathml3 valid in legacy

pages/legacy/content_publish.py, tests/legacy/ui/test_create_import_publish_module_and_collection.py
added test case for empty collection publish not allowed, added selector for non-authorized user
=> Added test case for empty collection publish not allowed

pages/legacy/collection_edit.py, pages/legacy/collections_confirm_remove.py, pages/legacy/my_cnx.py, pages/legacy/roles_edit.py, pages/legacy/workspace_collection.py, tests/legacy/ui/test_create_import_publish_module_and_collection.py
also construct page object for role_edit
=> Add test case for reorder-author

requirements.txt
updated cnx-litezip to 1.40 and neb to 5.1.0
=> updated cnx-litezip to 1.40 and neb to 5.1.0

pages/webview/content.py, tests/webview/ui/test_content.py
Fix sporadic StaleElementReferenceExceptions when accessing the title div's location and size
=> Fix section_title_div StaleElementReferenceException

pages/webview/content.py, tests/webview/ui/test_content.py, tests/webview/ui/test_home.py
This should fix many but not all of the webview marked tests.
There are still 1 or 2 broken tests remaining that need discussion, but this is one step closer to all those tests passing again.
=> Fix webview tests

tests/webview/ui/test_content.py
* Changed test to see if `OpenStax` is contained in the authors instead
of asserting exactness.
Fixes #351
=> Fixed test_author_is_openstax to test_author_contains_openstax

tests/webview/ui/test_home.py
added xfail to test_show_more_and_less due to bug not fixed soon
=> added xfail to test_show_more_and_less due to bug not fixed soon

.jenkins/testing, cli/neb.py, pages/webview/content.py, pages/webview/sitemap_index.py, parsers/cnx_deploy/requirements.py, parsers/cnx_deploy/version.py
Made change to .jenkins/testing file to fix name collision.
* added BUILD_NUMBER env var to TESTING_CONTAINER_NAME for more unique-ness
=> added BUILD_NUMBER env var to TESTING_CONTAINER_NAME for more unique-ness

.jenkins/testing
camelCase, it's like purposely adding dyslexia to your language. :stuck_out_tongue:
=> Fix a type in the pipeline-library function name

pages/webview/browse.py, tests/webview/ui/test_browse.py, tests/webview/ui/test_content.py
fix search tests and books button tests
=> fix search tests and books button tests

tests/webview/ui/test_content.py
removed xfail from canonical link tests
=> removed xfail from canonical link tests

patches/connection_reset_by_peer.py, requirements.txt
* We implemented a patch b/c of an issue with Travis and selenium. I'm
removing the patch to see if the problem still exists.
* Update pytest to 4.0.0
* Update selenium to 3.141.0
=> See if patch is still needed and update selenium and pytest.

.travis.yml, README.md, requirements.txt
added pytest-xdist plugin to run tests in parallel
=> added pytest-xdist plugin to run tests in parallel

Jenkinsfile
It'd be great if the tests always passed, but moving parts don't really allow for that just yet.
So rather than wait for everything to pass, let's release what we've got. This allows for the acceptance of pull requests that might parts of the failing situation without addressing everything. That might be just enough for part of the software suite to pass.
=> Always release the build regardless of test results

tests/webview/ui/test_content.py
removed 'College' from expected title assertion
=> removed 'College' from expected title assertion

pages/webview/content.py, tests/webview/ui/test_content.py
removed linkedin assertions from test and locators from PageObject
=> removed linkedin assertions from test and locators from PageObject

tests/webview/ui/test_content.py
removed linked in assertion for test_share_on_top_right
=> removed linked in assertion for test_share_on_top_right

tests/webview/ui/test_content.py
=> removed linked in reference

pages/webview/content.py, tests/webview/ui/test_content.py
* The section title was not included from the search result. A property
was added that has the title and chapter section for the assert.
=> fixed test_in_book_search by included chapter section in title

pages/webview/content.py, tests/webview/ui/test_content.py
=> Fix test book title link

requirements.txt, tests/conftest.py, tests/markers.py
* Updated pytest to 4.1.0
* Updated pytest-selenium to 1.15.1
* Added pytest_collection_modify_items function to conftest.py to mark
tests as run slow and replaced the marker from tests/markers.py to use
this new marker.
=> Updated pytest, updated pytest-selenium, and fixed usage of global pytest.config

.env.example, README.md
* Added a  .env.example file to the project
* Added instructions on how to copy the example file
=> Add .env.example file to the project

pages/webview/content.py, setup.cfg, tests/webview/ui/test_content.py
=> Fixed canonical link test

tests/webview/ui/test_content.py
baked book index page wasn't loaded. updated the index page uuid
=> baked book index page wasn't loaded. updated the index page uuid

.ci/pipeline.yml
* Added .ci folder
* Added initial pipeline.yml file 
* Added a job that builds and uploads the docker image to hub.docker.com
=> added build and publish job in concourse pipeline

Jenkinsfile
remove build and publish stage from jenkins pipeline
=> remove build and publish stage from jenkins pipeline

.ci/pipeline.yml
added slack resource and slack updates to #qa-stream on pipeline status
=> added slack resource and slack updates to #qa-stream on pipeline status

tests/webview/ui/test_content.py, tests/webview/ui/test_version.py
Updated test_toc_navigation to use a chapter with section number
=> Updated test_toc_navigation to use a chapter with section number

tests/webview/ui/test_content.py
=> xfail the param that fails due to new chapter review sub-collection

.ci/.pyup.yml, pages/webview/content_status.py, requirements.txt
=> Update pytest to 4.3.1, certifi to 2019.3.9

README.md
updated readme to remove mention of tox and include base_url commands
=> updated readme to remove mention of tox and include base_url commands

.ci/webview-functional-tests-pipeline.yml, README.md, tests/markers.py, tests/webview/ui/test_browse.py, tests/webview/ui/test_content.py, tests/webview/ui/test_content_status.py, tests/webview/ui/test_donate.py, tests/webview/ui/test_home.py, tests/webview/ui/test_search.py
Added smoke test marker to tests for quick validation that cnx.org is up and running.
=> added smoke marker to tests

tests/webview/ui/test_content.py
* Updated parametrized book to Biology 2e version.
=> Fixed test_in_book_search by using Biology 2e

fixtures/webview.py, tests/webview/ui/test_sitemap.py
add smoke marker to test sitemap and remove unused imports
=> add smoke marker to test sitemap and remove unused imports

cli/neb.py, fixtures/snapshot.py, tests/neb/ui/test_get.py, tests/neb/ui/test_publish.py, tests/utils.py
As the title suggests: Add the ability to test the neb publish command. Also includes some basic tests.
=> Add the ability to test the neb publish command

requirements.txt
updated urllib3 due to GitHub security alert
=> updated urllib3 due to GitHub security alert

tests/artillery/README.md, tests/artillery/main.yml, tests/artillery/rex_urls.csv
- Install [Artillery.io](https://artillery.io) `npm install -g artillery`
- `artillery run tests/load_tests/main.yml`
https://github.com/openstax/cnx/issues/387
=> Load test REX redirects

.travis.yml, fixtures/rex.py, setup.cfg, tests/conftest.py, tests/markers.py, tests/rex/integration/test_redirection.py
**Solves issue**: https://github.com/openstax/cnx/issues/358
=> Create integration tests for rex redirects

.travis.yml
=> FIX add back webview base url

.travis.yml, README.md, tests/rex/integration/test_redirection.py, tests/webview/ui/test_search.py
=> Resolve failing tests

README.md, tests/conftest.py
Adds more description to the CLI args to show which ones are used by Travis and how others might be useful.
=> chore: clarify CLI args

.ci/webview-functional-tests-pipeline.yml
changed webhook to #ce-stream channel
=> changed webhook to #ce-stream channel

.dockerignore, Dockerfile
pinned the selenium-chrome-debug version 3.141.59 in Dockerfile
=> pinned the selenium-chrome-debug version 3.141.59 in Dockerfile

fixtures/base.py, pages/webview/home.py, requirements.in, requirements.txt, tests/webview/integration/test_rex_redirects.py, tests/webview/ui/test_content.py, tests/webview/ui/test_home.py
Updating flaky tests by adjusting loaded property to Home page
=> Fixing flaky tests by adjusting loaded property of Home page

requirements.txt
Pyup scheduled update 2019 09 01
=> Pyup scheduled update 2019 09 01

.circleci/config.yml, README.md, setup.cfg
Try circleci instead of travis for running tests.
=> Use circleci instead of Travis

tests/webview/ui/test_home.py
removed the test for the android app link in footer. it is no longer present on cnx
=> removed check for android app link from test_home.py

tests/webview/ui/test_content.py
Changed book uuid to a non-redirecting book, changed search term to a non-existing and has_results to False
("2d941ab9-ac5b-4eb8-b21c-965d36a4f296", "filanthropic", False, 0, True, False)
=> changed book uuid from Biology to Organizational Behavior

.concourse/webview-functional-tests-pipeline.yml
use master branch for cnx-automation or else :boom:
=> use master branch for cnx-automation or else :boom:

tests/webview/ui/test_sitemap.py
See openstax/cnx#727 for details
Note, the adjoining backend logic is yet to come...
=> Test for the inclusion and exclusion of derived copies in the sitemap

.concourse/tasks/test-webview-ui-circleci/script.bash
add result output to circleci concourse task
=> add result output to circleci concourse task

.concourse/build-publish-pipeline.yml
change build publish pipeline to use ce-stream webhook instead of QA
=> change build publish pipeline to use ce-stream webhook instead of QA

tests/conftest.py
as per your comment, I am adding vendor to the list in conftest.py
=> adding vendor to the list in conftest.py

tests/webview/ui/test_content.py
removed a test function due to lack of appropriate books
removed some collection from parametrize due to lack of appropriate books
=> changes made due to more files being redirected, running out of testable books

README.md
=> add password for VNC

.pre-commit-config.yaml, tests/webview/ui/test_content.py
had to change book list index from 0 to 1 as more and more books redirects.
Also, flake8 didn't like that there was no placeholder in f"... string, so I removed f
=> changed book index in test_content due to new redirecting books

tests/webview/ui/test_content.py
had to fix book and page ids as the content changed for them and was failing. only polish physics 1 seems to be good for this test
=> changes failing book:page ids

fixtures/s3_books_title_version_dict.py, tests/s3_bucket/test_s3_pages_content.py
I removed duplicate title check in another fixture and separated exceptions
=> removing duplicate title check and separating exception check

tests/webview/ui/test_content.py, tests/webview/ui/test_home.py
simplified the failing assertions for Show less/more links
=> Adjusted Show more/less assertions

tests/s3_bucket/test_github_content_collections.py, tests/s3_bucket/test_github_content_repos.py
added for both git content tests try - except error control
=> adding error control to git storage tests

tests/s3_bucket/test_s3_bucket_books.py
as per changes to my aws account, removed setting aws keys and added comment as to what is needed to be done to set them
=> removing aws access/secret keys and adding comment

pages/poet/base.py, pages/poet/home.py, tests/poet/test_poet_ui.py
tests poet ui automatically, preferably after new extension deploy
I would like to have devs opinion on the code, especially the login part
=> poet ui smoke test

fixtures/webview.py, tests/conftest.py
corrected 2 fixtures, so job urls are complete and correct
=> correcting fixtures for job urls

tests/s3_bucket/test_search_github_content_repos.py
just looking for an opinion/any issues with it
=> QA search tool to look through all index files in all content repos

tests/webview/integration/test_wipe_files.py
the last one. I forgot to change the file name in the wipe file...
=> amending the report file name in the wipe file

tests/s3_bucket/test_github_content_collections.py, tests/s3_bucket/test_github_content_media.py, tests/s3_bucket/test_github_content_meta_inf.py, tests/s3_bucket/test_github_content_modules.py
added tests to:
verify presence of meta-inf folder
verify presence of media folder
made some changes to verification code
renamed: test_github_content_repos.py -> test_github_content_modules.py
=> amending and adding more checks for content repos

fixtures/git_content_repos_bundle.py, tests/conftest.py, tests/s3_bucket/test_github_content_collections.py, tests/s3_bucket/test_github_content_media.py, tests/s3_bucket/test_github_content_meta_inf.py, tests/s3_bucket/test_github_content_modules_bundle.py
to avoid issues with maximum rersponse numbers with github api, I made a quick and simple adjustment to my tests
=> adjusting github tests to avoid github response max

fixtures/webview.py, tests/conftest.py
small adjustments for the new friday pipeline tests
variables are set in .env
=> adjustments for friday pipeline tests to create correct job links in the report csv

fixtures/git_content_repos_1.py, fixtures/git_content_repos_2.py, fixtures/git_content_repos_3.py, tests/conftest.py, tests/s3_bucket/test_github_content_modules_1.py, tests/s3_bucket/test_github_content_modules_2.py, tests/s3_bucket/test_github_content_modules_3.py
'{"message":"API rate limit exceeded for user ID 44207656.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}'.count
=> dividing test_github_content_modules test into 3 shorter tests as per issues with request limit
