openstax/cnx-automation

- pages/content.py
- tests/conftest.py
- tests/test_cnx_home.py
* added an additional wait for the title of the content
* broke up the splash text and nav bar check into two tests
* changed the implicit wait to 0 on the selenium fixture
> Fixed stale element exception for content page

- .gitignore
- pages/home.py
- setup.cfg
- tests/conftest.py
* Added the --html report command to setup.cfg in order to generate nice html reports
* Added a command line option --headless to indicate when to run the chrome driver headless.
* Added report files to .gitignore
> Added html report to setup.cfg for pytest and chrome headless cli option

- Dockerfile
This will run tox using python 3.5 which is not python 3.6 like we are doing development but it'll be a bit more work to get that fixed and I think it's ok. There isn't much difference in what we are doing between 3.5 and 3.6. The next version of Ubuntu will have Python 3.6 as default. I'm thinking we can roll with it for now. I'll log it as an issue and place a low priority on it.
> Add docker compose

- pages/webview/base.py
- pages/webview/content.py
- pages/webview/home.py
I ran this about 10 times and it passed every time.
Note how `super().loaded` is the last thing I check in each subclass. This actually matters. It was failing with `super().loaded` at the beginning of the condition.
> Fix webview stale element errors

- pages/webview/content.py
- tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/53
https://github.com/openstax/cnx-automation/issues/54
https://github.com/openstax/cnx-automation/issues/55
https://github.com/openstax/cnx-automation/issues/56
These tests do not actually click the links, they only test the link urls match a template.
> Added tests for social share links

- pages/webview/browse.py
The search page is fully loaded when the subject list is displayed
There's no need to check for the search field/button (which load before the list)
> Should fix stale element error in search page

- pages/legacy/base.py
- pages/legacy/confirm_publish.py
- pages/legacy/confirm_remove.py
- pages/legacy/login_form.py
- pages/legacy/module_edit.py
- pages/legacy/my_cnx.py
- pages/legacy/workspace.py
- regions/legacy/collection.py
- regions/legacy/content.py
- regions/legacy/my_account.py
- tests/legacy/ui/test_create_import_publish_remove_module_and_collection.py
- tests/legacy/ui/test_login_logout.py
Ross said this would be good to prevent the workspace from growing unbounded, potentially causing tests to take longer and longer.
Includes https://github.com/openstax/cnx-automation/pull/60, so probably merge that first, then rebase to master for smaller diff. Or just look at https://github.com/openstax/cnx-automation/pull/64/commits/46fa56826eaa577f08b2fb61edfd663018eda052 and https://github.com/openstax/cnx-automation/pull/64/commits/8f56b016448944ff1105e7ddc12b8935bc15779e for the diff after #60.
> Test that deletes all content from automation account's personal workspace

- tests/legacy/ui/test_login_logout.py
Literally every single other test also logs in, so no point in testing login by itself.
Less legacy tests also means a faster test suite since legacy is so slow.
Moved some of the assertions of these tests to the login/logout tests, which are still there (git thinks I renamed the tests but really I deleted them and moved the assertions).
> Remove legacy login-only tests

- tests/conftest.py
changes the way we import fixtures. this sets us up nicely to also import any plugins we decide to create within the project later down the road. I plan on creating a couple first within this repo and then splitting them out later when necessary.
> Import fixture refactor

- fixtures/base.py
- requirements.txt
Using the lxml library was the easiest way I found to pretty print (and print the tags without the namespaces).
> Don't print head tag when printing page source

- fixtures/base.py
```
=============================== warnings summary ===============================
tests/webview/ui/test_about.py::test_about_us_content_includes_openstax_goals
/home/travis/build/openstax/cnx-automation/fixtures/base.py:33: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
if head:
tests/webview/ui/test_about.py::test_about_us_content_links
/home/travis/build/openstax/cnx-automation/fixtures/base.py:33: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
if head:
tests/webview/ui/test_content.py::test_share_on_top_right_corner
/home/travis/build/openstax/cnx-automation/fixtures/base.py:33: FutureWarning: The behavior …
```
> Fix deprecation warning

- pages/webview/base.py
- pages/webview/home.py
Turns out the page nav first loads with 0 height, which makes tests fail when attempting to click it.
This PR attempts to make the home page wait until the page nav is displayed (and thus has > 0 height).
Should fix element not visible errors when trying to click the nav in the home page.
> Attempt to fix home page menu failures

- pages/legacy/confirm_publish.py
- pages/legacy/metadata_edit.py
- tests/utils.py
Fixes a sporadic failure in the legacy tests.
Also renamed max_tries to max_attempts.
> Retry legacy SiteError when creating module

- Makefile
- setup.cfg
A tool will be used to upload the report and this is made easier by
using the standalone report as it will base64 encode the logs and
images.
* Added `--self-contained` to setup.cfg pytest addopts
* Updated Makefile to remove report.html when `make clean` command is
used
> Changed the html report to be standalone

- tests/webview/ui/test_content.py
https://github.com/openstax/cnx-automation/issues/153
(The test already asserts this by checking that the elements are displayed after clicking the links)
> Add test case C162195 to test_id_links_and_back_button

- .travis.yml
- fixtures/snapshot.py
- requirements.txt
Only neb usage and get tests exist for now.
We should do this before upgrading to Neb 5.0.0 to ensure the tests still work for the latest version.
See also: https://github.com/openstax/cnx-automation/pull/196
> Added Neb to the Travis build matrix and updated it to 5.0.0

- fixtures/webview.py
- tests/webview/ui/test_content.py
The content_url fixture is no longer needed because the `Content` class takes care of it now.
> Made the NCY tests work with the URL_TEMPLATE in the Content page class

- .travis.yml
So they stay on QA even if we change the default URLs
> Locked Travis URLs

- fixtures/base.py
- pages/webview/base.py
- pages/webview/content.py
- pages/webview/home.py
- regions/webview/base.py
- tests/webview/ui/test_content.py
- tests/webview/ui/test_home.py
Includes https://github.com/openstax/cnx-automation/pull/204 to avoid conflicts
- Wait for the hamburger menu (nav_button in content page on low resolutions) to open
- Set window size in all tests to prevent different behavior due to larger monitors
> Make some tests that were failing locally less flaky

- pages/webview/search_results.py
Just in case webview takes longer than the Selenium timeout to return the search error message. Should help with failures due to the search timing out.
> Retry searches when we get a TimeoutError

- pages/webview/content.py
- tests/webview/ui/test_content.py
- Updated the names of books_containing tests to be more consistent.
- Updated the toc/book button to check if open before expecting the region to load.
- Added asserts that ensure the books button toggles the books containing side bar nav.
> Updated book button test to include button toggle

- pages/webview/content.py
- pages/webview/content_page.py
- tests/webview/ui/test_content.py
- Added missing @markers.webview to C195054
- C195055 now tests that the button opens/closes the BooksContaining tab
- Use version 3 for SjdU64Og since version 4 does not exist in prod
- Moved TableOfContents out of HeaderNav because the table of contents is really not in the header navigation menu. (git diff went crazy on this one due to the indentation change)
> Fix some tests that were generating incorrect results

- pages/webview/contact.py
- tests/webview/ui/test_contact.py
The contact page has changed considerably. There were various headers we checked for that have been removed.
* Changed `test_contact_has_correct_headers` to `test_contact_has_questions_header`
* Removed test_contact_has_location_map b/c map has been removed
* Removed unnecessary locators from contact page that were used for headers and map
> removed unneeded map test and updates to email and header tests

- requirements.txt
Reverts openstax/cnx-automation#332. simplejson 3.16.1 is not showing up on PyPi causing this to bomb. All tests had passed previously.
> Revert "Update simplejson to 3.16.1"

- .dockerfiles/cnx.vcl
- .dockerfiles/proxy-openstax-org.conf
- .dockerfiles/settings.js
- .jenkins/testing
- Dockerfile
- Makefile
- README.md
- docker-compose.yml
- tests/markers.py
- tests/webview/ui/test_browse.py
- tests/webview/ui/test_content.py
- tests/webview/ui/test_content_status.py
- tests/webview/ui/test_home.py
- tests/webview/ui/test_robots.py
- tests/webview/ui/test_sitemap.py
- tests/webview/ui/test_version.py
This uses the latest webview and cnx-archive images to test a (partial) containerized environment.
Usage at the moment is `make test-webview`, which build the local selenium container, acquires the slim dump for data and executes the tests when things are ready.
This is a bit heavy... Lift with your legs not with your back. 😛
> Testing webview and archive integration using the latest images

- tests/webview/ui/test_browse.py
We can't reliably test the counts for each subject when using the test dataset
(i.e. lean dump). When working with a test dataset
not all subjects will have content. Therefore, we test that
at least one of the subjects has a count. This effectively tests
the communication between the browser and the web api as well as the
browser's ability to render the results.
> Test the subject counts give an almost accurate response

- .travis.yml
The data is more up-to-date on staging.cnx.org.
> Run travis-ci against staging.cnx.org instead of qa.cnx.org

- tests/webview/ui/test_content.py
The previous test for the figure's text isn't valid for this content, since
the figure itself doesn't have text. We'll end up with the same expected
results if we test for figures in general.
> Correct unicode title test expectations

- Makefile
- tests/markers.py
- tests/webview/ui/test_content.py
These tests have been marked as needing the complete dataset
because they use data/content that is not openstax specific.
These tests will therefore only work on deployed environments.
> Add a marker for requiring a complete dataset (i.e prod)

- .jenkins/testing
- .jenkins/testing.env.list
This sets up the jenkins job to test branches as well as `master`. When `master` passes tests, it is released to the Container Registry as `openstax/cnx-automation:latest`, which then means it active for use by other `cnx-*` repos during their functional testing stages.
Ah yes... 🍹 development workflow simplified. 🏖
> Release the latest container build when tests pass for the master branch

- pages/webview/base.py
- tests/webview/ui/test_content.py
* Changed the page to visit for checking anchor links.
* Fixed deprecation message on base page about using self.selenium
instead of self.driver.
* Removed assert for `#` in `new_url` to an assert on the id returned by the re.search.
> fixed id links and back button test

- .jenkins/testing
This is a quick fix to ensure the container name is unique.
Instead of using a generic name and incremental build number,
use the job name with the incremental build number
> Fix jenkins testing container name uniqueness

- pages/webview/content.py
- tests/webview/ui/test_content.py
* Removed epub assertions from tests and locators from page object.
* Refactored the tests to look for either PDF or the offline zip and the
footer if they exist.
> Fixed test_get_this_book button by removing epub option

- tests/webview/ui/test_home.py
This test would fail randomly b/c of a book title that was changed to be
all uppercase. This causes the similarity ratio to be too low and fails
the test. The solution is to force the titles to be lowercase before
their similarity ratio is calculated.
* Updated the test_title_link_loads_correct_page test by having the
titles be lowercase before being passed into the similar function.
> Fixed test_title_link_loads_correct_page test by making titles lowercase

- pages/webview/content.py
- tests/webview/ui/test_content.py
* The result.title_with_chapter_section was returning the section
number twice. It looks like we no longer need to format that and we can
go with the title.
* The search result now has figures so this was made to true.
> Fixed test_in_book_search by using full title

- Dockerfile
It's not exactly clear that openstax/selenium-chrome-debug comes from the openstax/docker-qa repo. This just points that out.
> Comment about where this base image comes from

- tests/conftest.py
- tests/markers.py
pytest is now enforcing that markers be registered by producing errors at the end of test runs:  
https://docs.pytest.org/en/latest/example/markers.html#registering-markers
- Added configuration options to register all markers via `pytest_configure` in `conftest.py`
Example of error:
```
PytestUnknownMarkWarning: Unknown pytest.mark.testrail - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
PytestUnknownMarkWarning,
```
Note: `markers.py` is staying relatively unchanged at this point as it acts as a convenience module to allow adding of markers ; additionally, it would break everything if removed and needs more testing.
```python
@markers.webview
def test_foo_feature(selenium, base_url):
pass
```
> fixed register marker errors with exclusion of testrail

- tests/webview/ui/test_home.py
Test would fail intermittently b/c a random book is being selected and
that random book could be a released rex book which would cause
timeouts. Problem corrected by continuously selecting random books until
a non-rex book is found.
> Fixed test_title_link_loads_correct_page intermittent failure due to rex redirect

- tests/webview/integration/test_rex_redirects.py
function 'test_redirecting_to_rex_from_within_webview' had an incorrect marker webview. changed it to rex.
> test_redirecting_to_rex_from_within_webview: changed marker from webview to rex

- pages/webview/donate.py
test_donate.py failed because the donate url changed. new address is https://riceconnect.rice.edu/donation/support-openstax
> changed donate url to the current new one

- tests/archive/integration/test_redirects.py
- tests/conftest.py
- tests/markers.py
- tests/webview/integration/test_archive_redirects.py
Test should run in cnx-automation by using:
```shell
pytest -m archive --webview-base-url https://qa.cnx.org --legacy-base-url https://legacy-qa.cnx.org --archive-base-url https://archive-qa.cnx.org
```
> add test that archive redirects respect host header

- tests/webview/ui/test_content.py
previous collection:page short ids failed and remained hanging. changed it to 
pytest.param("TqqPA4io:_LheuYk4") in
test_content:test_chapter_review_version_matches_book_version
> fixing hanging collection id in test_content

- tests/webview/vendorbooks/test_vendorpages_load.py
'Rozwiazania zadan' section became composite and find_element_by_link_text no longer worked. Had to change it to a different link name.
> changed find_element_by_link_text for polish books due to book changes

- fixtures/snapshot.py
The `metadata.json` files populated during `neb get` include a field
that incorporates the archive hostname causing tests to fail when
comparing snapshots generated across different environments. This
change causes the field to be ignored when comparing snapshots to
avoid these false positive failures.
> Ignore `canon_url` when comparing snapshots

- tests/neb/ui/test_publish.py
This addresses an issue with the modified test failing in python 3.8.
> Fix assert to force stdout to string

- fixtures/webview.py
- tests/conftest.py
- tests/s3_bucket/test_s3_pages_content.py
s3 bucket book verification: added fixtures for code_tag and queue_state_bucket_name, so when they change, we can supply them as command lines via pytest
> added fixtures for code_tag and queue_state_bucket_name

- fixtures/bucket_books_tree.py
removed and consolidated the code as per this comment in other PR:
I believe you can insert the results into book_tree in the try block while iterating on approved_books_full_url instead of using approved_books_full_url_modified as an intermediate list you iterate on in a second pass.
> adjusting the s3 bucket fixture code as per Ripal's comment

- Dockerfile
we did this small change a long time ago with Mike, to get selenium-chrome-debug version latest and not a fixed version
I never pushed the change to master
> Dockerfile: changing chrome-debug version to latest

- tests/webview/ui/test_content.py
Due to redirecting books, some webview tests failed. Had to:
- changed collection index to non-redirecting book
- simplified assertion condition for checking social media (facebook, twitter and linkedin)
> amended webview tests to elimate fails due to redirecting books

- tests/webview/ui/test_content.py
I changed tested book index to 32 (Fyzika dla skol vyssich - polish). This collection remains non-dericting longer and I am able to assert more complete urls.
> adjusting share assertions for a diff non-redirecting collection

- tests/s3_bucket/test_github_content_collections.py
- tests/s3_bucket/test_github_content_repos.py
Adding another testing for git content repos - to verify that collection.xml files are not empty
Also, I made 2 little changes to test_github_content_repos.py, which was approved in a previous PR
> test to verify collection.xml files in content repos

- fixtures/webview.py
@rnathuji changed concourse base url and added another fixture for webhosting env
.env now contains 3 variables
CODE_TAG
WEB_HOSTING_ENV
CONCOURSE_BASE_URL
> changed some variables as per discussion with Ripal

- tests/webview/integration/test_rex_redirects5.py
these are amendments to my redirect test in cnx-automation repo (test_rex_redirects.py) as per discussions from few weeks back. As per Phil's comments I removed checking page slugs and added checking for response.status_code. Anything different than 200 is then written out to a csv file which then can be checked by Neil and others to investigate while the book page fails. I assign this to @philschatz as per his explanation/advise and/or @rnathuji
> amending qa redirect test to check for 200 and non-200 status codes for each page url variation
